import 'package:hive/hive.dart';

part 'news_model.g.dart'; // This file is be generated by build_runner

@HiveType(typeId: 0)
class NewsModel extends HiveObject {
  @HiveField(0)
  final String? author;

  @HiveField(1)
  final String? title;

  @HiveField(2)
  final String? description;

  @HiveField(3)
  final String? imageUrl;

  @HiveField(4)
  final String? publishedAt;

  @HiveField(5)
  final String? content;

  @HiveField(6)
  int? hiveKey; // this will store the key assigned by Hive

  NewsModel({
    this.author,
    this.title,
    this.description,
    this.imageUrl,
    this.publishedAt,
    this.content,
    this.hiveKey,
  });

  factory NewsModel.fromJson(Map<String, dynamic> json) => NewsModel(
    author: json['author'],
    title: json['title'],
    description: json['description'],
    imageUrl: json['urlToImage'],
    publishedAt: json['publishedAt'],
    content: json['content'],
  );

  Map<String, dynamic> toJson() => {
    'author': author,
    'title': title,
    'description': description,
    'urlToImage': imageUrl,
    'publishedAt': publishedAt,
    'content': content,
  };

  static final emptyNewsModel = NewsModel(
    author: '',
    title: '',
    description: '',
    imageUrl: '',
    publishedAt: '',
    content: '',
  );
}

// class NewsModel {
//   final String? author;
//   final String? title;
//   final String? description;
//   final String? imageUrl;
//   final String? publishedAt;
//   final String? content;

//   const NewsModel({
//     this.author,
//     this.title,
//     this.description,
//     this.imageUrl,
//     this.publishedAt,
//     this.content,
//   });

//   factory NewsModel.fromJson(Map<String, dynamic> json) {
//     return NewsModel(
//       author: json['author'],
//       title: json['title'],
//       description: json['description'],
//       imageUrl: json['urlToImage'], // map to correct key
//       publishedAt: json['publishedAt'],
//       content: json['content'],
//     );
//   }

//   Map<String, dynamic> toJson() {
//     return {
//       'author': author,
//       'title': title,
//       'description': description,
//       'urlToImage': imageUrl,
//       'publishedAt': publishedAt,
//       'content': content,
//     };
//   }

//   static const emptyNewsModel = NewsModel(
//     author: '',
//     title: '',
//     description: '',
//     imageUrl: '',
//     publishedAt: '',
//     content: '',
//   );
// }
